/*
================================================================================
HEALTHCARE DATA PLATFORM - 05 GRANTS & PERMISSIONS
================================================================================
Execution Order: 5 of 7
Dependencies: 04_databases_schemas.sql
Purpose: Grant database, schema, and object permissions to roles

RUN AS: ACCOUNTADMIN

PERMISSION MATRIX:
┌──────────────────┬───────────────┬────────────────┬──────────────────────────┐
│ Role             │ Database      │ Schema Access  │ Table Permissions        │
├──────────────────┼───────────────┼────────────────┼──────────────────────────┤
│ HEALTHCARE_ADMIN │ All           │ ALL + CREATE   │ Full control             │
│ HEALTHCARE_ENG   │ RAW, TRANSFORM│ USAGE + CREATE │ SELECT, INSERT, UPDATE   │
│ HEALTHCARE_ANALY │ ANALYTICS     │ USAGE          │ SELECT only              │
│ HEALTHCARE_SCI   │ AI_READY      │ USAGE + CREATE │ SELECT, INSERT, UPDATE   │
│ HEALTHCARE_VIEW  │ ANALYTICS     │ USAGE          │ SELECT only              │
└──────────────────┴───────────────┴────────────────┴──────────────────────────┘
================================================================================
*/

-- ============================================================================
-- STEP 5.1: Database Grants
-- ============================================================================
-- ADMIN: Full access to all databases
GRANT ALL ON DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_ADMIN;

-- ENGINEER: Access to Bronze and Silver layers
GRANT USAGE ON DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT USAGE ON DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ENGINEER;

-- ANALYST: Access to Gold layer
GRANT USAGE ON DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;

-- SCIENTIST: Access to Platinum layer
GRANT USAGE ON DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_SCIENTIST;

-- VIEWER: Read access to Gold layer (base role)
GRANT USAGE ON DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;

-- ============================================================================
-- STEP 5.2: Schema Grants - ADMIN (Full Control)
-- ============================================================================
GRANT ALL ON ALL SCHEMAS IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_ADMIN;

-- Future schemas auto-grant for ADMIN
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ADMIN;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_ADMIN;

-- ============================================================================
-- STEP 5.3: Schema Grants - ENGINEER (Bronze + Silver)
-- ============================================================================
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ENGINEER;

-- Future schemas for ENGINEER
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ENGINEER;

-- ============================================================================
-- STEP 5.4: Schema Grants - ANALYST (Gold - Read Only)
-- ============================================================================
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;

-- ============================================================================
-- STEP 5.5: Schema Grants - SCIENTIST (Platinum)
-- ============================================================================
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_SCIENTIST;
GRANT CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_SCIENTIST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_SCIENTIST;

-- ============================================================================
-- STEP 5.6: Schema Grants - VIEWER (Gold - Read Only)
-- ============================================================================
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;

-- ============================================================================
-- STEP 5.7: Table/View Grants (Current + Future Objects)
-- ============================================================================

-- ENGINEER: Full table access on Bronze/Silver
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE HEALTHCARE_RAW_DB TO ROLE HEALTHCARE_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE HEALTHCARE_TRANSFORM_DB TO ROLE HEALTHCARE_ENGINEER;

-- ANALYST: Read-only on Gold
GRANT SELECT ON ALL TABLES IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_ANALYST;

-- SCIENTIST: Full table access on Platinum
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_SCIENTIST;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE HEALTHCARE_AI_READY_DB TO ROLE HEALTHCARE_SCIENTIST;

-- VIEWER: Read-only on Gold
GRANT SELECT ON ALL TABLES IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;
GRANT SELECT ON ALL VIEWS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;
GRANT SELECT ON FUTURE TABLES IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HEALTHCARE_ANALYTICS_DB TO ROLE HEALTHCARE_VIEWER;

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SHOW GRANTS TO ROLE HEALTHCARE_ADMIN;
SHOW GRANTS TO ROLE HEALTHCARE_ENGINEER;
SHOW GRANTS TO ROLE HEALTHCARE_ANALYST;
SHOW GRANTS TO ROLE HEALTHCARE_SCIENTIST;
SHOW GRANTS TO ROLE HEALTHCARE_VIEWER;
